version: '3.9'
services:
  app:
    image: alpine:latest
    command: "sleep 1000"
    volumes:
      - "12345test:/tmp"
    environment:
      - MYSQL_HOST=test
    labels:
      biz.aventer.mesos_compose.container_type: "DOCKER"
      traefik.enable: "true"
      traefik.http.routers.test.entrypoints: "web"
      traefik.http.routers.test.service: "mc:test:app:80"
      traefik.http.routers.test.rule: "HostRegexp(`example.com`, `{subdomain:[a-z]+}.example.com`)"
    network_mode: "BRIDGE"
    network: default
    networks:
      default:
        aliases:
          - "test.example.de"
    pull_policy: always
    ports:
      - "8080:80"
    cap_add:
      - SYS_ADMIN
    cap_drop:
      - NET_ADMIN
    deploy:
      placement:
        constraints:
          - "node.hostname==localhost"
      replicas: 1
      resources:
        limits:
          cpus: "0.01"
          memory: "50"

networks:
  default:
    external: true
    name: weave

volumes:
  12345test:
    driver: local
