## This is an example of all supported parameters

version: '3.9'

services:
  app:
    image: alpine:latest
    command: "sleep 1000"
    restart: always
    volumes:
      - "12345test:/tmp"
    environment:
      - MYSQL_HOST=test
    hostname: test
    container_name: test
    labels:
      biz.aventer.mesos_compose.container_type: "DOCKER"
      bis.aventer.mesos_compose.task_name: "mc:test:app1" # an alternative taskname
      biz.aventer.mesos_compose.executor: "./my-custom-executor"
      biz.aventer.mesos_compose.executor_uri: "http://localhost/my-custom-executor"
      traefik.enable: "true"
      traefik.http.routers.test.entrypoints: "web"
      traefik.http.routers.test.service: "mc:test:app1:80" # if an alternative taskname is set, we have to use it here to
      traefik.http.routers.test.rule: "HostRegexp(`example.com`, `{subdomain:[a-z]+}.example.com`)"
    network_mode: "BRIDGE"
    ports:
      - "8080:80"
      - "9090"
      - "8081:81/tcp"
      - "8082:82/udp"
    network: default
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 
        hard: 65536
    deploy:
      placement:
        constraints:
          - "node.hostname==localhost"
          - "node.platform.os==linux"
          - "node.platform.arch==arm"
      replicas: 1
      resources:
        limits:
          cpus: 0.01
          memory: 50

networks:
  default:
    external: true
    name: weave
    driver: bridge

volumes:
  12345test:
    driver: local


