version: '3.9'
services:
  test1:
    image: debian:11
    command: "sleep 1"
    environment:
      - FIRECRACKER_WORKDIR=/usr/libexec/mesos 
      - FIRECRACKER_AGENT_PORT=8080
    labels:
      biz.aventer.mesos_compose.executor: "/usr/libexec/mesos/mesos-firecracker-executor"
      biz.aventer.mesos_compose.executor_uri: '[{"Value":"https://raw.githubusercontent.com/AVENTER-UG/mesos-util/master/types.go","OutputFile":"mesos-firecracker-executor"}]'
      biz.aventer.mesos_compose.container_type: "DOCKER"
      
