version: '3.9'
services:
  test1:
    image: avhost/firecracker:latest
    command: "sleep 1"
    environment:
      - FIRECRACKER_WORKDIR=/tmp
      - FIRECRACKER_AGENT_PORT=8080
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    privileged: true        
    mesos:
      executor:
        command: "/tmp/mesos-firecracker-executor"
    pull_policy: always
    restart: no
      
