version: '3.9'
services:
  test1:
    image: avhost/firecracker:latest
    command: "sleep 1"
    environment:
      - FIRECRACKER_WORKDIR=/tmp
      - FIRECRACKER_AGENT_PORT=8080
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    privileged: true        
    labels:
      biz.aventer.mesos_compose.executor: "/tmp/mesos-firecracker-executor"
      biz.aventer.mesos_compose.container_type: "DOCKER"
    pull_policy: always
      
