version: '3.9'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    hostname: mongo.mc.mesos
    image: mongo:5.0
    network: graylog
    volumes:
      - /data/graylog/data/mongodb:/data/db
    ports:
      - 27017:27017
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
  opensearch:
    image: opensearchproject/opensearch:2.0.1
    container_name: mc.test.opensearch.mc.mesos
    environment:
      cluster.name: opensearch-cluster
      node.name: mc.test.opensearch.mc.mesos
      bootstrap.memory_lock: false # along with the memlock settings below, disables swapping
      discovery.type: single-node
      plugins.security.disabled: true
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      DISABLE_INSTALL_DEMO_CONFIG: true" # disables execution of install_demo_configuration.sh bundled with security plugin, which installs demo certificates and security configurations to OpenSearch
      DISABLE_SECURITY_PLUGIN: true" # disables security plugin entirely in OpenSearch by setting plugins.security.disabled: true in opensearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    ports:
      - 9200:9200
    network: graylog
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: 0.01
          memory: 2000
    volumes:
      - /data/graylog/data/esdb:/usr/share/elasticsearch/data

  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:5.0.1
    environment:
      # CHANGE ME!
      GRAYLOG_PASSWORD_SECRET: xaesh1Sualu0yahg
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_MONGODB_URI: mongodb://mc.test.mongo.mc.mesos:27017/graylog        
      GRAYLOG_ELASTICSEARCH_HOSTS: http://mc.test.opensearch.mc.mesos:9200
    network: graylog
    restart: always
    deploy:
      resources:
        limits:
          memory: 1000
    depends_on:
      - mongo
      - elasticsearch
    labels:
      traefik.enable: "true"
      traefik.http.routers.__mesos_taskid__.entrypoints: "web"
      traefik.http.routers.__mesos_taskid__.rule: "Host(`your.example.com`)"
      traefik.http.routers.__mesos_taskid__.service: "mc:test:graylog:9000"
      traefik.http.routers.__mesos_taskid__.middlewares: "graylog-header"
      traefik.http.middlewares.graylog-header.headers.customrequestheaders.X-Graylog-Server-URL: "http://your.example.com:9080/"
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp

networks:
  graylog:
    name: mesos-net

