version: '3.9'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    hostname: mongo.mini
    image: mongo:5.0
    network: graylog
    volumes:
      - /data/graylog/data/mongodb:/data/db
    ports:
      - 27017:27017
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docker.html
  elasticsearch:
    hostname: elasticsearch.mini
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 2000
    network: graylog
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /data/graylog/data/esdb:/usr/share/elasticsearch/data
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    hostname: graylog.mini
    image: graylog/graylog:5.0.1
    environment:
      # CHANGE ME!
      - GRAYLOG_PASSWORD_SECRET=xaesh1Sualu0yahg
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_MONGODB_URI=mongodb://mongo.mini:27017/graylog        
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch.mini:9200
    network: graylog
    restart: always
    deploy:
      resources:
        limits:
          memory: 1000
    depends_on:
      - mongo
      - elasticsearch
    labels:
      traefik.enable: "true"
      traefik.http.routers.__mesos_taskid__.entrypoints: "web"
      traefik.http.routers.__mesos_taskid__.rule: "Host(`your.example.com`)"
      traefik.http.routers.__mesos_taskid__.service: "mc:test:graylog:9000"
      traefik.http.routers.__mesos_taskid__.middlewares: "graylog-header"
      traefik.http.middlewares.graylog-header.headers.customrequestheaders.X-Graylog-Server-URL: "http://your.example.com:9080/"
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp

networks:
  graylog:
    name: mini

