version: '3.9'
services:
  test-extension:
    image: docker.io/avhost/docker-lighttpd
    restart: always
    labels:
      traefik.enable: "true"
      traefik.http.routers.test1.entrypoints: "web"
      traefik.http.routers.test1.rule: "Host(`www.example.com`)"
      traefik.http.routers.test1.service: "mc_homepages_test1_8888"
      traefik.http.services.test1.loadBalancer.healthCheck.path: "/index.html"
      traefik.http.services.test1.loadBalancer.healthCheck.interval: "10s"
      traefik.http.services.test1.loadBalancer.healthCheck.timeout: "3s"
    network: default
    ports:
      - 8880:8080
      - 2222:8081
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50"

networks:
  default:
    name: mini
          
