version: '3.9'
services:
  test1:
    image: docker.io/avhost/docker-lighttpd
    ports:
      - "0:8888/h2c"
    network_mode: "bridge"    
    labels:
      traefik.enable: "true"
      traefik.http.routers.test1.entrypoints: "web"
      traefik.http.routers.test1.rule: "Host(`www.example.com`)"
      traefik.http.routers.test1.service: "mc.test_test1:8888"
    network: default
    restart: always

networks:
  default:
    external: true
    name: mini
          
