version: '3.9'
services:
  test1:
    image: docker.io/avhost/docker-lighttpd
    ports:
      - "9999:8888/http"
    labels:
      traefik.enable: "true"
      traefik.http.routers.__mesos_taskid__.entrypoints: "web"
      traefik.http.routers.__mesos_taskid__.rule: "Host(`your.example.com`)"
      traefik.http.routers.__mesos_taskid__.service: "__mesos_portname__"
      traefik.http.services.__mesos_taskid__.loadBalancer.healthCheck.path: "/index.html"
      traefik.http.services.__mesos_taskid__.loadBalancer.healthCheck.interval: "10s"
      traefik.http.services.__mesos_taskid__.loadBalancer.healthCheck.timeout: "3s"
    restart: always
    network_mode: "user"    
    network: default
    deploy:
      replicas: 1

networks:
  default:
    name: weave
    driver: weave
