version: '3.9'
services:
  test1:
    image: docker.io/avhost/docker-lighttpd
    ports:
      - "9999:8888/http"
    labels:
      traefik.enable: "true"
      traefik.http.routers.test1.entrypoints: "web"
      traefik.http.routers.test1.rule: "Host(`your.example.com`)"
      traefik.http.routers.test1.service: "mc_test_test1_8888"
      traefik.http.services.test1.loadBalancer.healthCheck.path: "/index.html"
      traefik.http.services.test1.loadBalancer.healthCheck.interval: "10s"
      traefik.http.services.test1.loadBalancer.healthCheck.timeout: "3s"
    restart: always
    network_mode: "user"    
    network: default
    deploy:
      replicas: 1

networks:
  default:
    name: mesos-net
    driver: mesos-net
