version: '3.9'
services:
  test1:
    image: docker.io/avhost/docker-lighttpd
    ports:
      - "9999:8888/http"
    network_mode: "bridge"
    hostname: test.weave.local
    labels:
      traefik.enable: "true"
      traefik.http.routers.test1.entrypoints: "web"
      traefik.http.routers.test1.rule: "Host(`your.example.com`)"
      traefik.http.routers.test1.service: "mc_test_test1_8888"
      traefik.http.services.test1.loadBalancer.healthCheck.path: "/index.html"
      traefik.http.services.test1.loadBalancer.healthCheck.interval: "10s"
      traefik.http.services.test1.loadBalancer.healthCheck.timeout: "3s"
    network: default
    restart: always
    deploy:
      replicas: 1
