version: '3.9'
services:
  test1:
    image: alpine
    restart: always
    environment:
      - test=vault://secret/data/abd
    network: default
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50"

          
