[book]
authors = ["Andreas Peters"]
language = "en"
multilingual = false
src = "src"
title = "Mesos Compose - The Docker-Compose Orchestrator for Mesos

[build]
create-missing = true
preprocess = ["links", "index"]
